#!/bin/bash 
#$ -cwd 
#$ -S /bin/bash 
#$ -P large_mem
# Keep standard error and standard out separate. To join, use -j y 
#$ -j y 
#$ -V 
# make sure to reserve resources
#$ -R y
#$ -o /srv/gs1/projects/bustamante/rmccoy_projects/results/trinity_logs
#$ -e /srv/gs1/projects/bustamante/rmccoy_projects/results/trinity_logs
#  set the working directory
#$ -wd /srv/gs1/projects/bustamante/rmccoy_projects/results/trinity_output
# email address to send notices to
#$ -M rmccoy@stanford.edu
# Send email when job begins and ends 
#$ -m beas
# request enough RAM... 
#$ -l h_vmem=120G
# Send to extended queue 
#$ -q large


PATH=$PATH\:/srv/gs1/projects/bustamante/progs/bowtie-0.12.7; export PATH
module rm java/latest
module add java/6u35
ulimit -a


#note that Trinity_kN.pl files are simple modifications to the Trinity.pl script to change variable $IWORM_KMER_SIZE = 25 to $IWORM_KMER_SIZE = N.

/home/jokelley/tools/trinityrnaseq_r2012-10-05/Trinity_k21.pl --seqType fq --JM 80G --left /srv/gs1/projects/bustamante/rmccoy_projects/data/trinity_input/r1_combined.fastq --right /srv/gs1/projects/bustamante/rmccoy_projects/data/trinity_input/r2_combined.fastq --output /srv/gs1/projects/bustamante/rmccoy_projects/results/trinity_output/01-2013/kmer21/ --group_pairs_distance 300 --CPU 2 --bfly_opts "-V 10 --stderr"

/home/jokelley/tools/trinityrnaseq_r2012-10-05/Trinity_k23.pl --seqType fq --JM 80G --left /srv/gs1/projects/bustamante/rmccoy_projects/data/trinity_input/r1_combined.fastq --right /srv/gs1/projects/bustamante/rmccoy_projects/data/trinity_input/r2_combined.fastq --output /srv/gs1/projects/bustamante/rmccoy_projects/results/trinity_output/01-2013/kmer23/ --group_pairs_distance 300 --CPU 2 --bfly_opts "-V 10 --stderr"

/home/jokelley/tools/trinityrnaseq_r2012-10-05/Trinity_k25.pl --seqType fq --JM 110G --left /srv/gs1/projects/bustamante/rmccoy_projects/data/trinity_input/r1_combined.fastq --right /srv/gs1/projects/bustamante/rmccoy_projects/data/trinity_input/r2_combined.fastq --output /srv/gs1/projects/bustamante/rmccoy_projects/results/trinity_output/01-2013/kmer25/ --group_pairs_distance 300 --CPU 4 --bfly_opts "-V 10 --stderr"

/home/jokelley/tools/trinityrnaseq_r2012-10-05/Trinity_k27.pl --seqType fq --JM 110G --left /srv/gs1/projects/bustamante/rmccoy_projects/data/trinity_input/r1_combined.fastq --right /srv/gs1/projects/bustamante/rmccoy_projects/data/trinity_input/r2_combined.fastq --output /srv/gs1/projects/bustamante/rmccoy_projects/results/trinity_output/01-2013/kmer27/ --group_pairs_distance 300 --CPU 4 --bfly_opts "-V 10 --stderr"

/home/jokelley/tools/trinityrnaseq_r2012-10-05/Trinity_k29.pl --seqType fq --JM 110G --left /srv/gs1/projects/bustamante/rmccoy_projects/data/trinity_input/r1_combined.fastq --right /srv/gs1/projects/bustamante/rmccoy_projects/data/trinity_input/r2_combined.fastq --output /srv/gs1/projects/bustamante/rmccoy_projects/results/trinity_output/01-2013/kmer29/ --group_pairs_distance 300 --CPU 4 --bfly_opts "-V 10 --stderr"

/home/jokelley/tools/trinityrnaseq_r2012-10-05/Trinity_k31.pl --seqType fq --JM 110G --left /srv/gs1/projects/bustamante/rmccoy_projects/data/trinity_input/r1_combined.fastq --right /srv/gs1/projects/bustamante/rmccoy_projects/data/trinity_input/r2_combined.fastq --output /srv/gs1/projects/bustamante/rmccoy_projects/results/trinity_output/01-2013/kmer31/ --group_pairs_distance 300 --CPU 4 --bfly_opts "-V 10 --stderr"
